# Generated by Django 4.1 on 2023-12-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identifiers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('long_url', models.TextField()),
                ('short_url', models.CharField(max_length=256)),
                ('user_identifier', models.CharField(blank=True, max_length=256, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='identifiers',
            index=models.Index(fields=['user_identifier'], name='urlshortene_user_id_ce11f3_idx'),
        ),
    ]
