# Generated by Django 4.1 on 2023-12-08 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identifiers',
            old_name='short_url',
            new_name='short_url_key',
        ),
    ]
