# Generated by Django 4.1 on 2023-12-10 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_rename_short_url_identifiers_short_url_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identifiers',
            options={'ordering': ['-date_added']},
        ),
    ]
